#%RAML 1.0 NamedExample
value:
  input:
    [
      businessEntity: trafficLights,
      attribute: colours
    ]
  output:
    [
      [
        SAP: red,
        CRM: red,
        Web: red
      ],
      [
        SAP: amber,
        CRM: yellow,
        Web: yellow
      ],
      [
        SAP: green,
        CRM: green,
        Web: none
      ]
    ]