#%RAML 1.0 NamedExample
value:
  input:
    [
      businessEntity: trafficLights,
      attribute: colours,
      query: "CRM, red"
    ]
  output:
    [
      [
        SAP: red,
        CRM: red,
        Web: red
      ]
    ]