INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (1, 'TrafficLights', 'Colours', 'SAP', 'red', 'STOP');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (2, 'TrafficLights', 'Colours', 'CRM', 'red', 'STOP');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (3, 'TrafficLights', 'Colours', 'WEB', 'red', 'STOP');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (4, 'TrafficLights', 'Colours', 'SAP', 'amber', 'WAIT');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (5, 'TrafficLights', 'Colours', 'CRM', 'yellow', 'WAIT');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (6, 'TrafficLights', 'Colours', 'WEB', 'yellow', 'WAIT');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (7, 'TrafficLights', 'Colours', 'SAP', 'green', 'GO');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (8, 'TrafficLights', 'Colours', 'CRM', 'green', 'GO');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (9, 'TrafficLights', 'Colours', 'WEB', 'none', 'GO');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (10, 'Translate', 'Language', 'GB', 'Mr', 'MR');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (11, 'Translate', 'Language', 'NL', 'Dhr', 'MR');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (12, 'Translate', 'Language', 'D', 'Herr', 'MR');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (20, 'Special', 'Many', 'System1', '1,2,3', '3-5');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (21, 'Special', 'Many', 'System2', '4,5,6,7,8', '3-5');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (22, 'Special', 'Many', 'System1', '{"Name":"A. Grimm","Employeer":"Mulesoft"}', 'JSON');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (23, 'Special', 'Many', 'System2', '{"Name":"Andreas Grimm","Arbeitgeber":"Mulesoft"}', 'JSON');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (30, 'Special', 'Many', 'Main Course', 'Spare-Rips', 'OR');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (31, 'Special', 'Many', 'Drinks', 'Beer', 'OR');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (32, 'Special', 'Many', 'Drinks', 'Red Vine', 'OR');
INSERT INTO "DataTable" ("Key", "Entity", "Attribute", "System", "Value", "Group") VALUES (33, 'Special', 'Many', 'Drinks', 'Pepsi', 'OR');
