#%RAML 1.0 Trait

queryParameters:
  system:
    description: |
              application name of the value to be translated. This limits the return only to the corresponding key / value pair list which translate to the search parameters.
    type: string
  value:
    description: |
              value to be translated. This limits the return only to the corresponding key / value pair list which translate to the search parameters.
    type: string